apiVersion: v1
kind: ServiceAccount
metadata:
  name: imposter-sa
  namespace: workloads
---
apiVersion: v1
kind: Pod
metadata:
  name: imposter
  namespace: workloads
  labels:
    app: imposter
    spiffe.io/spire-managed-identity: "true"
  annotations:
    inject.istio.io/templates: sidecar
spec:
  serviceAccountName: imposter-sa
  containers:
    - name: service-a
      image: 628409561582.dkr.ecr.eu-central-1.amazonaws.com/bridge-the-gap/service-a:v3
      ports:
        - containerPort: 8080
      env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/secrets/workload-spiffe-uds/socket
        - name: SERVICE_B_BASE_URL
          value: https://20.103.67.78:8080
        - name: SERVICE_B_SPIFFE_ID
          value: spiffe://azure.bridgethegap.local/ns/workloads/sa/service-b
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - mountPath: /run/secrets/workload-spiffe-uds
          name: spiffe-workload-api
          readOnly: true
  volumes:
    - name: spiffe-workload-api
      csi:
        driver: csi.spiffe.io
        readOnly: true
