apiVersion: v1
kind: Namespace
metadata:
  name: workloads
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b
  namespace: workloads
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: workloads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
        spiffe.io/spire-managed-identity: "true"
      annotations:
        inject.istio.io/templates: "sidecar"
        traffic.sidecar.istio.io/excludeInboundPorts: "8080"
    spec:
      serviceAccountName: service-b
      containers:
        - name: service-b
          image: acrbridgethegapxdd129.azurecr.io/service-b:v4
          ports:
            - containerPort: 8080
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: "unix:///run/secrets/workload-spiffe-uds/socket"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /run/secrets/workload-spiffe-uds
              readOnly: true
        - name: opa
          image: openpolicyagent/opa:1.16.2-static
          args:
            - "run"
            - "--server"
            - "--addr=localhost:8181"
            - "--set=decision_logs.console=true"
            - "/policy/policy.rego"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: opa-policy
              mountPath: /policy
              readOnly: true
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: csi.spiffe.io
            readOnly: true
        - name: opa-policy
          configMap:
            name: opa-policy
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: workloads
spec:
  selector:
    app: service-b
  ports:
    - port: 80
      targetPort: 8080
