apiVersion: v1
kind: Namespace
metadata:
  name: workloads
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b
  namespace: workloads
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: workloads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
        spiffe.io/spire-managed-identity: "true"
      annotations:
        inject.istio.io/templates: "sidecar,spire"
    spec:
      serviceAccountName: service-b
      containers:
        - name: service-b
          image: acrbridgethegapxdd129.azurecr.io/service-b:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: workloads
spec:
  selector:
    app: service-b
  ports:
    - port: 80
      targetPort: 8080
