resource "aws_eks_cluster" "main" {
  name     = var.cluster_name
  role_arn = aws_iam_role.eks_cluster.arn

  vpc_config {
    subnet_ids              = concat(aws_subnet.public[*].id, aws_subnet.private[*].id)
    endpoint_public_access  = true
    endpoint_private_access = false
  }

  depends_on = [aws_iam_role_policy_attachment.eks_cluster_policy]
}

resource "aws_eks_node_group" "main" {
  cluster_name           = aws_eks_cluster.main.name
  node_group_name_prefix = "${var.cluster_name}-ng-"
  node_role_arn          = aws_iam_role.eks_node.arn
  subnet_ids             = aws_subnet.private[*].id

  instance_types = ["m7i-flex.large"]
  capacity_type  = "ON_DEMAND"

  scaling_config {
    desired_size = 2
    min_size     = 2
    max_size     = 2
  }

  depends_on = [
    aws_iam_role_policy_attachment.eks_node_worker_policy,
    aws_iam_role_policy_attachment.eks_node_cni_policy,
    aws_iam_role_policy_attachment.eks_node_ecr_policy,
  ]

  lifecycle {
    create_before_destroy = true
  }
}

# EKS-managed vpc-cni addon with Network Policy support enabled.
# Previously vpc-cni ran "self-managed" (installed by default when the
# cluster was created, but not tracked as a Terraform-managed addon), with
# ENABLE_NETWORK_POLICY unset (defaults to false) - any Kubernetes
# NetworkPolicy applied was completely ignored at the network layer
# (verified live: zero PolicyEndpoint objects generated by aws-eks-nodeagent
# for a test policy). Bringing it under Terraform explicitly, with network
# policy enforcement turned on, so the deny-by-default policies in k8s/ are
# actually enforced, not just API objects with no effect.
resource "aws_eks_addon" "vpc_cni" {
  cluster_name                = aws_eks_cluster.main.name
  addon_name                  = "vpc-cni"
  addon_version               = "v1.22.4-eksbuild.3"
  resolve_conflicts_on_create = "OVERWRITE"
  resolve_conflicts_on_update = "OVERWRITE"

  configuration_values = jsonencode({
    enableNetworkPolicy = "true"
  })

  depends_on = [aws_eks_node_group.main]
}
